-- MySQL Script generated by MySQL Workbench
-- Fri Oct 10 22:52:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Articulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Articulo` (
  `id_articulo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  `costo_importacion` DECIMAL(12,2) UNSIGNED NOT NULL,
  `precio_base` DECIMAL(12,2) UNSIGNED NOT NULL,
  `impuesto` INT UNSIGNED NOT NULL,
  `DetalleCompra_id_detalle_compra` BIGINT UNSIGNED NOT NULL,
  `InventarioSucursal_id_inventario` BIGINT UNSIGNED NOT NULL,
  `DetalleVenta_id_detalle_venta` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_articulo`),
  CONSTRAINT `fk_Articulo_DetalleCompra1`
    FOREIGN KEY (`DetalleCompra_id_detalle_compra`)
    REFERENCES `mydb`.`DetalleCompra` (`id_detalle_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_InventarioSucursal1`
    FOREIGN KEY (`InventarioSucursal_id_inventario`)
    REFERENCES `mydb`.`InventarioSucursal` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articulo_DetalleVenta1`
    FOREIGN KEY (`DetalleVenta_id_detalle_venta`)
    REFERENCES `mydb`.`DetalleVenta` (`id_detalle_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `codigo_UNIQUE` ON `mydb`.`Articulo` (`codigo` ASC) VISIBLE;

CREATE INDEX `fk_Articulo_DetalleCompra1_idx` ON `mydb`.`Articulo` (`DetalleCompra_id_detalle_compra` ASC) VISIBLE;

CREATE INDEX `fk_Articulo_InventarioSucursal1_idx` ON `mydb`.`Articulo` (`InventarioSucursal_id_inventario` ASC) VISIBLE;

CREATE INDEX `fk_Articulo_DetalleVenta1_idx` ON `mydb`.`Articulo` (`DetalleVenta_id_detalle_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`AuditoriaUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AuditoriaUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AuditoriaUsuario` (
  `id_auditoria` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `accion` VARCHAR(100) NOT NULL,
  `maquina` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_auditoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoriaProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CategoriaProducto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CategoriaProducto` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL,
  `Articulo_id_articulo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_categoria`),
  CONSTRAINT `fk_CategoriaProducto_Articulo1`
    FOREIGN KEY (`Articulo_id_articulo`)
    REFERENCES `mydb`.`Articulo` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_categoria_UNIQUE` ON `mydb`.`CategoriaProducto` (`nombre_categoria` ASC) VISIBLE;

CREATE INDEX `fk_CategoriaProducto_Articulo1_idx` ON `mydb`.`CategoriaProducto` (`Articulo_id_articulo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `identificacion` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` VARCHAR(20) NULL,
  `correo` VARCHAR(100) NULL,
  `Venta_id_venta` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `fk_Cliente_Venta1`
    FOREIGN KEY (`Venta_id_venta`)
    REFERENCES `mydb`.`Venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `identificacion_UNIQUE` ON `mydb`.`Cliente` (`identificacion` ASC) VISIBLE;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `mydb`.`Cliente` (`correo` ASC) VISIBLE;

CREATE INDEX `fk_Cliente_Venta1_idx` ON `mydb`.`Cliente` (`Venta_id_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `id_compra` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  `id_sucursal` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(12,2) UNSIGNED NOT NULL,
  `DetalleCompra_id_detalle_compra` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `fk_Compra_DetalleCompra1`
    FOREIGN KEY (`DetalleCompra_id_detalle_compra`)
    REFERENCES `mydb`.`DetalleCompra` (`id_detalle_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Compra_DetalleCompra1_idx` ON `mydb`.`Compra` (`DetalleCompra_id_detalle_compra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DetalleCompra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DetalleCompra` (
  `id_detalle_compra` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_articulo` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `costo_unitario` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_detalle_compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DetalleVenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DetalleVenta` (
  `id_detalle_venta` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_venta` BIGINT UNSIGNED NOT NULL,
  `id_articulo` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio_unitario` DECIMAL(12,2) UNSIGNED NOT NULL,
  `descuento` DECIMAL(5,2) UNSIGNED NULL DEFAULT 0,
  `impuesto` DECIMAL(5,2) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id_detalle_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `id_empleado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_sucursal` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `Venta_id_venta` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_empleado`),
  CONSTRAINT `fk_Empleado_Venta1`
    FOREIGN KEY (`Venta_id_venta`)
    REFERENCES `mydb`.`Venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `mydb`.`Empleado` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_Empleado_Venta1_idx` ON `mydb`.`Empleado` (`Venta_id_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Impuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Impuesto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Impuesto` (
  `id_impuesto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_impuesto` VARCHAR(50) NOT NULL,
  `porcentaje` DECIMAL(5,2) UNSIGNED NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `Articulo_id_articulo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_impuesto`),
  CONSTRAINT `fk_Impuesto_Articulo1`
    FOREIGN KEY (`Articulo_id_articulo`)
    REFERENCES `mydb`.`Articulo` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_impuesto_UNIQUE` ON `mydb`.`Impuesto` (`nombre_impuesto` ASC) VISIBLE;

CREATE INDEX `fk_Impuesto_Articulo1_idx` ON `mydb`.`Impuesto` (`Articulo_id_articulo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`InventarioSucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InventarioSucursal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InventarioSucursal` (
  `id_inventario` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_sucursal` INT UNSIGNED NOT NULL,
  `id_articulo` INT UNSIGNED NOT NULL,
  `stock_actual` INT UNSIGNED NOT NULL DEFAULT 0,
  `stock_minimo` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_inventario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `uq_sucursal_articulo` ON `mydb`.`InventarioSucursal` (`id_sucursal` ASC, `id_articulo` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `id_pago` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_venta` BIGINT UNSIGNED NOT NULL,
  `id_tipo_pago` INT UNSIGNED NOT NULL,
  `monto` DECIMAL(12,2) UNSIGNED NOT NULL,
  `moneda` ENUM('Bs', 'USD', 'EUR') NOT NULL,
  `id_tasa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `rif` VARCHAR(20) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(30) NULL,
  `email` VARCHAR(100) NULL,
  `Compra_id_compra` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  CONSTRAINT `fk_Proveedor_Compra1`
    FOREIGN KEY (`Compra_id_compra`)
    REFERENCES `mydb`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rif_UNIQUE` ON `mydb`.`Proveedor` (`rif` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`Proveedor` (`email` ASC) VISIBLE;

CREATE INDEX `fk_Proveedor_Compra1_idx` ON `mydb`.`Proveedor` (`Compra_id_compra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reporte` (
  `id_reporte` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_reporte` VARCHAR(50) NOT NULL,
  `fecha_generacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_usuario` INT UNSIGNED NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `id_rol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `Usuario_id_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rol`),
  CONSTRAINT `fk_Rol_Usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_rol_UNIQUE` ON `mydb`.`Rol` (`nombre_rol` ASC) VISIBLE;

CREATE INDEX `fk_Rol_Usuario_idx` ON `mydb`.`Rol` (`Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `id_sucursal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `Empleado_id_empleado` INT UNSIGNED NOT NULL,
  `Compra_id_compra` BIGINT UNSIGNED NOT NULL,
  `InventarioSucursal_id_inventario` BIGINT UNSIGNED NOT NULL,
  `Venta_id_venta` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  CONSTRAINT `fk_Sucursal_Empleado1`
    FOREIGN KEY (`Empleado_id_empleado`)
    REFERENCES `mydb`.`Empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Compra1`
    FOREIGN KEY (`Compra_id_compra`)
    REFERENCES `mydb`.`Compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_InventarioSucursal1`
    FOREIGN KEY (`InventarioSucursal_id_inventario`)
    REFERENCES `mydb`.`InventarioSucursal` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Venta1`
    FOREIGN KEY (`Venta_id_venta`)
    REFERENCES `mydb`.`Venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `mydb`.`Sucursal` (`nombre` ASC) VISIBLE;

CREATE INDEX `fk_Sucursal_Empleado1_idx` ON `mydb`.`Sucursal` (`Empleado_id_empleado` ASC) VISIBLE;

CREATE INDEX `fk_Sucursal_Compra1_idx` ON `mydb`.`Sucursal` (`Compra_id_compra` ASC) VISIBLE;

CREATE INDEX `fk_Sucursal_InventarioSucursal1_idx` ON `mydb`.`Sucursal` (`InventarioSucursal_id_inventario` ASC) VISIBLE;

CREATE INDEX `fk_Sucursal_Venta1_idx` ON `mydb`.`Sucursal` (`Venta_id_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TasaCambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TasaCambio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TasaCambio` (
  `id_tasa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `valor` DECIMAL(12,2) UNSIGNED NOT NULL,
  `id_usuario_autorizado` INT UNSIGNED NOT NULL,
  `estado` ENUM('vigente', 'historica') NOT NULL DEFAULT 'vigente',
  `Venta_id_venta` BIGINT UNSIGNED NOT NULL,
  `Pago_id_pago` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_tasa`),
  CONSTRAINT `fk_TasaCambio_Venta1`
    FOREIGN KEY (`Venta_id_venta`)
    REFERENCES `mydb`.`Venta` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TasaCambio_Pago1`
    FOREIGN KEY (`Pago_id_pago`)
    REFERENCES `mydb`.`Pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TasaCambio_Venta1_idx` ON `mydb`.`TasaCambio` (`Venta_id_venta` ASC) VISIBLE;

CREATE INDEX `fk_TasaCambio_Pago1_idx` ON `mydb`.`TasaCambio` (`Pago_id_pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoPago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoPago` (
  `id_tipo_pago` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL,
  `Pago_id_pago` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_tipo_pago`),
  CONSTRAINT `fk_TipoPago_Pago1`
    FOREIGN KEY (`Pago_id_pago`)
    REFERENCES `mydb`.`Pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_tipo_UNIQUE` ON `mydb`.`TipoPago` (`nombre_tipo` ASC) VISIBLE;

CREATE INDEX `fk_TipoPago_Pago1_idx` ON `mydb`.`TipoPago` (`Pago_id_pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `clave_hash` VARCHAR(255) NOT NULL,
  `id_rol` INT UNSIGNED NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL DEFAULT 'activo',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AuditoriaUsuario_id_auditoria` BIGINT UNSIGNED NOT NULL,
  `Empleado_id_empleado` INT UNSIGNED NOT NULL,
  `TasaCambio_id_tasa` INT UNSIGNED NOT NULL,
  `Reporte_id_reporte` BIGINT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_Usuario_AuditoriaUsuario1`
    FOREIGN KEY (`AuditoriaUsuario_id_auditoria`)
    REFERENCES `mydb`.`AuditoriaUsuario` (`id_auditoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empleado1`
    FOREIGN KEY (`Empleado_id_empleado`)
    REFERENCES `mydb`.`Empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_TasaCambio1`
    FOREIGN KEY (`TasaCambio_id_tasa`)
    REFERENCES `mydb`.`TasaCambio` (`id_tasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Reporte1`
    FOREIGN KEY (`Reporte_id_reporte`)
    REFERENCES `mydb`.`Reporte` (`id_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `mydb`.`Usuario` (`id_usuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `nombre_usuario_UNIQUE` ON `mydb`.`Usuario` (`nombre_usuario` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_AuditoriaUsuario1_idx` ON `mydb`.`Usuario` (`AuditoriaUsuario_id_auditoria` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_Empleado1_idx` ON `mydb`.`Usuario` (`Empleado_id_empleado` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_TasaCambio1_idx` ON `mydb`.`Usuario` (`TasaCambio_id_tasa` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_Reporte1_idx` ON `mydb`.`Usuario` (`Reporte_id_reporte` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `id_venta` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_empleado` INT UNSIGNED NOT NULL,
  `id_sucursal` INT UNSIGNED NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(12,2) UNSIGNED NOT NULL,
  `moneda` ENUM('Bs', 'USD', 'EUR') NOT NULL,
  `id_tasa` INT UNSIGNED NOT NULL,
  `DetalleVenta_id_detalle_venta` BIGINT UNSIGNED NOT NULL,
  `Pago_id_pago` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venta`),
  CONSTRAINT `fk_Venta_DetalleVenta1`
    FOREIGN KEY (`DetalleVenta_id_detalle_venta`)
    REFERENCES `mydb`.`DetalleVenta` (`id_detalle_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Pago1`
    FOREIGN KEY (`Pago_id_pago`)
    REFERENCES `mydb`.`Pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Venta_DetalleVenta1_idx` ON `mydb`.`Venta` (`DetalleVenta_id_detalle_venta` ASC) VISIBLE;

CREATE INDEX `fk_Venta_Pago1_idx` ON `mydb`.`Venta` (`Pago_id_pago` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
